app:
  name: 'logi-track'
  version: '1.0.0'

log:
  level: "debug"

postgres:
  max_pool_size: 12

grpc:
  port: 3000

prometheus:
  port: 9000

rest:
  port: 8080

broker:
  brokers_address:
    - "localhost:9092"
  topic: "notifications"